/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package com.mycompany.modull4;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SENJU
 */
public class no1 extends javax.swing.JInternalFrame {
    DefaultListModel<String> list1 = new DefaultListModel<>(); //mengelola daftar tugas
    DefaultListModel<String> list2 = new DefaultListModel<>();
    String matkul;
    String deadline;
    String detail;
    int angka=1;


    /** Creates new form no1 */
    public no1() {
        initComponents();
        jList.setModel(list1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tDeadline = new javax.swing.JTextField();
        tMatkul = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDetail = new javax.swing.JTextArea();
        cReset = new javax.swing.JButton();
        cSimpan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jHapus = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTugas = new javax.swing.JTextArea();
        jBersihkan = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("MV Boli", 1, 12)); // NOI18N
        jLabel4.setText("Nama Mata Kuliah");

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(217, 142, 142));

        jPanel3.setBackground(new java.awt.Color(234, 162, 162));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 26)); // NOI18N
        jLabel1.setText("Tambah Tugas Baru");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 12)); // NOI18N
        jLabel2.setText("Detail Tugas");

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 12)); // NOI18N
        jLabel3.setText("Nama Mata Kuliah");

        jLabel5.setFont(new java.awt.Font("MV Boli", 1, 12)); // NOI18N
        jLabel5.setText("Deadline Tugas");

        tDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDeadlineActionPerformed(evt);
            }
        });

        tMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMatkulActionPerformed(evt);
            }
        });

        tDetail.setColumns(20);
        tDetail.setRows(5);
        jScrollPane1.setViewportView(tDetail);

        cReset.setBackground(new java.awt.Color(255, 102, 102));
        cReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cReset.setText("Reset");
        cReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cResetActionPerformed(evt);
            }
        });

        cSimpan.setBackground(new java.awt.Color(255, 102, 102));
        cSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cSimpan.setText("Simpan");
        cSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(cReset)
                .addGap(76, 76, 76)
                .addComponent(cSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cReset)
                    .addComponent(cSimpan))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tambah Tugas", jPanel4);

        jPanel2.setBackground(new java.awt.Color(236, 155, 176));

        jPanel5.setBackground(new java.awt.Color(234, 173, 193));

        jLabel6.setFont(new java.awt.Font("Gabriola", 1, 26)); // NOI18N
        jLabel6.setText("Daftar Tugas");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jList.setModel(list1);
        jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList);

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel7.setText("Detail Tugas");

        jHapus.setBackground(new java.awt.Color(255, 153, 204));
        jHapus.setText("Hapus");
        jHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusActionPerformed(evt);
            }
        });

        jTugas.setRows(5);
        jScrollPane4.setViewportView(jTugas);

        jBersihkan.setBackground(new java.awt.Color(255, 153, 204));
        jBersihkan.setText("Bersihkan");
        jBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBersihkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jHapus)
                        .addGap(34, 34, 34)
                        .addComponent(jBersihkan)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHapus)
                            .addComponent(jBersihkan))
                        .addGap(14, 14, 14))))
        );

        jTabbedPane2.addTab("Daftar Tugas", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDeadlineActionPerformed

    private void tMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMatkulActionPerformed

    private void cSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSimpanActionPerformed
        matkul = tMatkul.getText();
        deadline = tDeadline.getText();
        detail = tDetail.getText();

        if (matkul.isEmpty() || deadline.isEmpty() || detail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukan Data Dengan Benar!! dan isi Semuanya");
        }else {
        list1.addElement(angka + "." + matkul + " (DL : " + deadline + ")");
        list2.addElement(detail);
        
        tMatkul.setText("");
        tDeadline.setText("");
        tDetail.setText("");
        
         JOptionPane.showMessageDialog(this,"Data Berhasil diSimpan");
         angka++;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cSimpanActionPerformed

    private void cResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cResetActionPerformed
        tMatkul.setText("");
        tDeadline.setText("");
        tDetail.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_cResetActionPerformed

    private void jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMouseClicked
        if (evt.getClickCount() == 1) {
            int pilihIndex = jList.locationToIndex(evt.getPoint());
        if (pilihIndex >= 0) {
           // Mendapatkan nilai dari elemen yang dipilih
           String pilihdetail = list2.getElementAt(pilihIndex);
           jTugas.setText(pilihdetail);
       }
   }
        // TODO add your handling code here:
    }//GEN-LAST:event_jListMouseClicked

    private void jHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusActionPerformed

         int selectedIndex = jList.getSelectedIndex();
    
        if (selectedIndex >= 0) {
            list1.remove(selectedIndex);
            jTugas.setText("");
        } else {
        JOptionPane.showMessageDialog(this, "Pilih list tugas untuk dihapus");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jHapusActionPerformed

    private void jBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBersihkanActionPerformed
        list1.clear();
        detail ="";
        jTugas.setText(detail);
        angka=1;
    // TODO add your handling code here:
    }//GEN-LAST:event_jBersihkanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cReset;
    private javax.swing.JButton cSimpan;
    private javax.swing.JButton jBersihkan;
    private javax.swing.JButton jHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTugas;
    private javax.swing.JTextField tDeadline;
    private javax.swing.JTextArea tDetail;
    private javax.swing.JTextField tMatkul;
    // End of variables declaration//GEN-END:variables

}
